version: '3.5'

services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=recipe_app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=recipe_app
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  # broker:
  #   image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"
    ports:
    - "6379:6379"

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      # - broker
      # - result
      - frontend

  # celery:
  #   build:
  #     dockerfile: backend/Dockerfile
  #     context: .
  #   command: celery --app=myproject worker --loglevel=info
  #   volumes:
  #     - ./:/home/user/app/
  #   env_file: backend/.env
  #   depends_on:
  #     - db
  #     - broker
  #     - result

  # mailhog: # service for faking a SMTP server
  #   image: mailhog/mailhog
  #   ports:
  #     - '1025:1025' # smtp server
  #     - '8025:8025' # web ui

volumes:
  dbdata:
    name: recipe_app_dbdata
    external: true
